language: android

node_js:
  - 4.4.7

notifications:
  email: false

sudo: false

branches:
  only:
  - master

install:
  - npm install -g npm@3.10.7
  - npm cache clean
  - npm install
  - npm install -g cordova ionic
  - echo y | android update sdk -u --filter android-22,android-23

before_script:
  - cordova platform rm android
  - cordova platform add android

script:
  - cordova prepare
  - cordova build android --release -- --ant
  
release:
  - exit 0  
