sudo: false
language: android
cache:
  directories:
    - node_modules
notifications:
  email: false
android:
    components:
        - build-tools-23.0.1
        - android-23
jdk:
  - oraclejdk8
before_install:
  - nvm install v4
  - npm i -g npm@^2.0.0
  - npm install -g ionic
  - npm install -g cordova
  - echo y | android update sdk -u --filter android-22,android-23
install:
  - npm install
before_script:
  - npm prune
  - ionic platform add android
script:
  - ionic build android
